name: ID Bulucu

on:
  workflow_dispatch: # Butona basınca çalışır

jobs:
  find-id:
    runs-on: ubuntu-latest

    steps:
      - name: Dosyaları Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests python-dotenv

      - name: ID Bulma Kodunu Çalıştır
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          # Database ID'yi henüz bilmediğimiz için buraya koymadık, kod zaten arayıp bulacak.
        run: python bul.py
