name: Notion Besin Yükleyici

# Bu action ne zaman çalışsın?
on:
  workflow_dispatch: # "Run workflow" butonuna basınca çalışır.
  # push:            # Eğer her 'Save' (commit) yaptığında çalışsın istersen bu satırın başındaki # işaretini kaldır.

jobs:
  add-food-data:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests python-dotenv

      - name: Scripti Çalıştır (main.py)
        env:
          # GitHub Secrets'tan şifreleri alıp koda veriyoruz
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
